name: CD Example - Deploy Text File

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Deployment Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout deployment
          git merge main --no-edit
          git push origin deployment
